# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d54fff2b25583bbe3ecca16d345b81bb7669d80a09f09ecfb2048321eb4af465608b217470e13c147982fe2099a5582f6d0516b47e95dcf2c9fc5270398044c7

test:
  secret_key_base: 49662ebc0014f27f6d3723ae6da4dfa4c60068367496373a0b3eea2a4a7ad09dea36d56ce8967967bc423ef55f3c14b14380389cee8558bee9c07ed24903d0d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
